### PR TITLE
Markdown lint

### PR DESCRIPTION
**Pull request by justinabrahms**
Refs https://github.com/open-feature/spec/issues/36

May close it out entirely, depending on how strongly we feel about auto-TOC. 

If we want that, we might explore this: https://github.com/marketplace/actions/toc-generator. The [other options](https://stackoverflow.com/questions/9721944/automatic-toc-in-github-flavoured-markdown) I saw didn't seem the greatest. (pandoc doesn't pass lint, for example)

### CODE REVIEW

**Comment by justinabrahms** [comment]
Looks like wrapping is causing our rendering to not have spaces in the json. I'll need to look into that.

**Review by oleg-nenashev — APPROVED** [review]
I would not enforce such short line breaks, but otherwise looks ok

**Comment by justinabrahms** [comment]
I don't much care of the line lengths, but we should pick some standard. Happy to pick something else. 🤷‍♂️

**Comment by justinabrahms** [comment]
Merging now so as to not cause a million merge conflicts for someone else. If we want to change the line length, that seems fine to me.

**Pull request merged**
